import Tarefa from '#models/tarefa'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { Nivel } from '../../contracts/enum/nivel.js'
import { Frequencia } from '../../contracts/enum/frequencia.js'
import { Status } from '../../contracts/enum/status.js'


export default class TarefaSeeder extends BaseSeeder {
  public async run () {

    await Tarefa.createMany([
      {
        titulo: 'Enviar relatório semanal',
        status: Status.PENDENTE,
        descricao: 'Enviar relatório do time até sexta-feira.',
        prazo: '2025-02-10',
        frequencia: Frequencia.SEMANAL,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.ALTA,
        num_categoria: 1,
        num_recompensa: 1,
        criado_por: 11111111111,
      },
      {
        titulo: 'Fazer compras do mês',
        status: Status.PENDENTE,
        descricao: 'Ir ao mercado e repor itens essenciais.',
        prazo: '2025-02-08',
        frequencia: Frequencia.MENSAL,
        nivel_energia_fisica: Nivel.ALTA,
        nivel_energia_mental: Nivel.MODERADA,
        num_categoria: 2,
        num_recompensa: 2,
        criado_por: 22222222222,
      },
      {
        titulo: 'Estudar para prova',
        status: Status.PENDENTE,
        descricao: 'Revisar capítulo 5 e exercícios.',
        prazo: '2025-02-12',
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.INTENSA,
        num_categoria: 3,
        num_recompensa: 3,
        criado_por: 33333333333,
      },
      {
        titulo: 'Consulta médica',
        status: Status.PENDENTE,
        descricao: 'Consulta com clínico geral.',
        prazo: '2025-02-11',
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.MODERADA,
        num_categoria: 4,
        num_recompensa: 4,
        criado_por: 44444444444,
      },
      {
        titulo: 'Pagar contas',
        status: Status.PENDENTE,
        descricao: 'Pagar energia, água e internet.',
        prazo: '2025-02-09',
        frequencia: Frequencia.MENSAL,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.MODERADA,
        num_categoria: 5,
        num_recompensa: 5,
        criado_por: 55555555555,
      },
      {
        titulo: 'Organizar guarda-roupa',
        status: Status.PENDENTE,
        descricao: 'Separar roupas para doação.',
        prazo: '2025-02-15',
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.ALTA,
        nivel_energia_mental: Nivel.MODERADA,
        num_categoria: 6,
        num_recompensa: 6,
        criado_por: 66666666666,
      },
      {
        titulo: 'Entrega de projeto',
        status: Status.PENDENTE,
        descricao: 'Finalizar módulo do sistema.',
        prazo: '2025-02-13',
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.INTENSA,
        num_categoria: 7,
        num_recompensa: 7,
        criado_por: 77777777777,
      },
      {
        titulo: 'Ler 20 minutos',
        status: Status.PENDENTE,
        descricao: 'Leitura diária antes de dormir.',
        prazo: '2025-02-07',
        frequencia: Frequencia.DIARIA,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.MODERADA,
        num_categoria: 8,
        num_recompensa: 8,
        criado_por: 88888888888,
      },
      {
        titulo: 'Planejar viagem',
        status: Status.PENDENTE,
        descricao: 'Pesquisar destinos e valores.',
        prazo: '2025-02-20',
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.ALTA,
        num_categoria: 9,
        num_recompensa: 9,
        criado_por: 99999999999,
      },
      {
        titulo: 'Organizar planilha financeira',
        status: Status.PENDENTE,
        descricao: 'Atualizar gastos e receitas.',
        prazo: '2025-02-14',
        frequencia: Frequencia.SEMANAL,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.ALTA,
        num_categoria: 10,
        num_recompensa: 10,
        criado_por: 10101010101,
      },
    ])
  }
}
