import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { Nivel } from '../../contracts/enum/nivel.js'
import { Frequencia } from '../../contracts/enum/frequencia.js'
import { Status } from '../../contracts/enum/status.js'
import SubTarefa from '#models/sub_tarefa'

export default class SubTarefaSeeder extends BaseSeeder {
  public async run () {

    await SubTarefa.createMany([
      {
        titulo: 'Revisar texto inicial',
        descricao: 'Primeira leitura do documento.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.MODERADA,
        num_tarefa: 1,
        num_motivacao: 1,
        criado_por: 11111111111,
      },
      {
        titulo: 'Separar materiais',
        descricao: 'Organizar itens antes da execução.',
        ordem: 2,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.ALTA,
        nivel_energia_mental: Nivel.MODERADA,
        num_tarefa: 2,
        num_motivacao: 2,
        criado_por: 22222222222,
      },
      {
        titulo: 'Resolver exercícios',
        descricao: 'Completar os exercícios finais do capítulo.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.DIARIA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.ALTA,
        num_tarefa: 3,
        num_motivacao: 3,
        criado_por: 33333333333,
      },
      {
        titulo: 'Preparar documentos',
        descricao: 'Separar documentos solicitados.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.MODERADA,
        num_tarefa: 4,
        num_motivacao: 4,
        criado_por: 44444444444,
      },
      {
        titulo: 'Revisar pagamentos',
        descricao: 'Confirmar valores antes de pagar.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.MENSAL,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.MODERADA,
        num_tarefa: 5,
        num_motivacao: 5,
        criado_por: 55555555555,
      },
      {
        titulo: 'Separar roupas',
        descricao: 'Escolher roupas para doação.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.ALTA,
        nivel_energia_mental: Nivel.BAIXA,
        num_tarefa: 6,
        num_motivacao: 6,
        criado_por: 66666666666,
      },
      {
        titulo: 'Testar funcionalidades',
        descricao: 'Avaliar funções do módulo.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.INTENSA,
        num_tarefa: 7,
        num_motivacao: 7,
        criado_por: 77777777777,
      },
      {
        titulo: 'Registrar leitura',
        descricao: 'Anotar páginas lidas.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.DIARIA,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.MODERADA,
        num_tarefa: 8,
        num_motivacao: 8,
        criado_por: 88888888888,
      },
      {
        titulo: 'Comparar destinos',
        descricao: 'Listar prós e contras.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.UNICA,
        nivel_energia_fisica: Nivel.MODERADA,
        nivel_energia_mental: Nivel.ALTA,
        num_tarefa: 9,
        num_motivacao: 9,
        criado_por: 99999999999,
      },
      {
        titulo: 'Atualizar itens da planilha',
        descricao: 'Revisar gastos do mês atual.',
        ordem: 1,
        status: Status.PENDENTE,
        frequencia: Frequencia.SEMANAL,
        nivel_energia_fisica: Nivel.BAIXA,
        nivel_energia_mental: Nivel.ALTA,
        num_tarefa: 10,
        num_motivacao: 10,
        criado_por: 10101010101,
      },
    ])
  }
}
